### ISSUE TITLE
Requiring flatbuffers v1.12 is breaking tflite.convert()

### ISSUE THREAD

**Issue by CharlesMod** [Seeed-Studio/yolov5-swift#28]
### Search before asking

- [X] I have searched the YOLOv5-Swift [issues](https://github.com/Seeed-Studio/yolov5-swift/issues) and found no similar bug report.

### YOLOv5-Swift Component

Integrations, Other

### Bug

on line 496 there is a requirements check for flatbuffers v1.12, for my application (Seeed studio vision ai) this causes the conversion from a tf model to tflite model to fail on the convert function. 

Seems this was to solve an int8 flag related bug previously, that is now fixed as of the latest flatbuffers version. Simply removing this if statement restores functionality. 

### Environment

Google colab

### Minimal Reproducible Example

Without the fix, see [this ](https://colab.research.google.com/gist/lakshanthad/b47a1d1a9b4fac43449948524de7d374/yolov5-training-for-sensecap-a1101.ipynb)google colab notebook, things will error out on step 7 (assuming you place credentials in the earlier step)

### Additional

nope!

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mjq2020** [comment]
> ### Search before asking
> * [x]  I have searched the YOLOv5-Swift [issues](https://github.com/Seeed-Studio/yolov5-swift/issues) and found no similar bug report.
> 
> ### YOLOv5-Swift Component
> Integrations, Other
> 
> ### Bug
> on line 496 there is a requirements check for flatbuffers v1.12, for my application (Seeed studio vision ai) this causes the conversion from a tf model to tflite model to fail on the convert function.
> 
> Seems this was to solve an int8 flag related bug previously, that is now fixed as of the latest flatbuffers version. Simply removing this if statement restores functionality.
> 
> ### Environment
> Google colab
> 
> ### Minimal Reproducible Example
> Without the fix, see [this ](https://colab.research.google.com/gist/lakshanthad/b47a1d1a9b4fac43449948524de7d374/yolov5-training-for-sensecap-a1101.ipynb)google colab notebook, things will error out on step 7 (assuming you place credentials in the earlier step)
> 
> ### Additional
> nope!
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I'd like to help by submitting a PR!

![image](https://user-images.githubusercontent.com/74635395/219562379-5341a344-746e-412c-a008-4073126eec73.png)
Have you followed the steps in the picture?

**Comment by CharlesMod** [comment]
Yes.

**Comment by CharlesMod** [comment]
This isn't an issue with importing from roboflow, this is an issue with
exporting an already trained TF model
